---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: heading
  label: Content
- type: directory
  path: _songs
  label: Songs
  create: all
  match: "*"
- type: directory
  path: _paryayas
  label: Paryāẏa/পর্যায়
  create: all
  match: "*"
  templates:
  - paryaya
- type: directory
  path: _talas
  label: Tāla/তাল
  create: all
  match: "*"
  templates:
  - tala
- type: document
  path: _data/languages.yml
  label: Languages
- type: jekyll-pages
  label: Pages
  create: all
  templates:
  - landing-page
  - page
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":year:/:month:/:day:/:filename:"
build:
  preview_env:
  - JEKYLL_ENV=staging
  preview_output_directory: _site
  install_dependencies_command: bundle install --path vendor/bundle
  preview_docker_image: forestryio/ruby:2.6
  mount_path: "/srv"
  instant_preview_command: bundle exec jekyll serve --drafts --unpublished --future
    --port 8080 --host 0.0.0.0 -d _site
